### ISSUE TITLE
presentation: add reveal.js capabilities

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#236]

**Comment by McShelby** [comment]
First tests are a bit overcomplicated when using a separate theme like reveal-hugo.

A more integrated solution would be nicer but the requirements are not clear yet, eg.

- display fullscreen
- display in iframe
- keyboard controls
- speaker notes

**Comment by McShelby** [comment]
I can not see a reveal integration in the next few years done by me. 

Reasons are a) the unclear requirements and b) more important issues regarding already existing features.

So I drop it for now. Nevertheless I would be open for PRs for this.

**Comment by cagix** [comment]
@McShelby as far as i can see, you'd need to change the directory layout and also to deal with extra elements in the markdown files, i.e. filter or transform things like speaker notes when producing the hugo site and transform all the hugo shortcodes somehow when producing reveal.js slides. i'm kind of doing this in my repos (using latex/beamer instead of reveal.js), but it's not really fun. i really love your theme, but sadly hugo is ... quite "unfriendly" in this scenario.
