### ISSUE TITLE
initCodeClipboard() apparently does not respect disableInlineCopyToClipBoard = true setting

### ISSUE THREAD

**Issue by bwbecker** [McShelby/hugo-theme-relearn#273]
First of all, thank you for resurrecting the Learn theme as Relearn!  Very much appreciated :)

I'm chasing down a difference in my web site.  In the following screen grab there should be five checkboxes, not just four.  The `(init? x)` is shifted left in both places, hiding the checkbox in the first instance and some text in the second.  

![screenshot_098](https://user-images.githubusercontent.com/1038662/173875506-fe4077c4-574b-4785-a512-1469d8bcf865.png)

The `(list? x)` in both places has a class added to the `code` tag, `copy-to-clipboard-code`.  The `/code` tag is immediately followed by a `span` for a copy button that isn't actually showing up here.  I believe this is new behaviour.

I have `disableInlineCopyToClipBoard = true` set in my config file, which Relearn does not appear to be respecting in this case.

The `copy-to-clipboard-code` class is added by the `initCodeClipboard()` function in `theme.js`.  That's a new function; I'm not sure what its purpose is.  

There is, admittedly, some of my CSS involved here.  But I think that's beside the issue because I don't think the `copy-to-clipboard-code` class and then extra `span` should be added.

**Comment by bwbecker** [comment]
A bit more sleuthing...  The `code` tags are surrounded by a `span` with class `copy-to-clipboard`.  This is also new behaviour.  If I override `copy-to-clipboard` in my CSS to use `display: inline` rather than `display: inline-block` the overlap goes away.

But...  I still think these classes and spans should not be added if `disableInlineCopyToClipBoard` is specified.

**Comment by McShelby** [comment]
> First of all, thank you for resurrecting the Learn theme as Relearn! Very much appreciated :)

Thanks! <3

The inline-code underwent some major changes in #175 to add support for dark mode. Also it had issues with line breaks that were addressed as well.

Generating different DOM for differnt values of `disableInlineCopyToClipBoard` is a hassle, because then you have to provide a complete different set of CSS selectors to style both variants. It's easier to handle this in the CSS. That's the reason why the parameter is currently coverd in `stylesheet.html`.

The containing span does not have any margins at all. Also the layout of your screenshot looks unfamiliar to me. So without further markdown or a link to your page, there's nothing I can do at the moment. I assume this is a custom style of your installation.

**Comment by bwbecker** [comment]
Thanks for the explanation.  

The formatting shown above is generated by one of my shortcodes based on a data file and includes some of my own markup. 

The work-arounds listed above are working for me.  Guess I was just surprised by the new elements.
