### ISSUE TITLE
theme: Add Support for basic Quiz Functionality using Hugo quizdown.

### ISSUE THREAD

**Issue by Prakash4844** [McShelby/hugo-theme-relearn#507]
Hey, i think it would be awesome to have a basic quiz functionality support out of the box. 
i have already used it in my website.
![image](https://user-images.githubusercontent.com/81550376/227758442-3dac2029-654e-4f4d-9bbc-9bc4a20eef0c.png)

but i don't know about enough about hugo to integrate it in theme itself. 

Here is the link https://github.com/bonartm/hugo-quiz

**Comment by cagix** [comment]
That would be amazing! Could use that, too!

**Comment by McShelby** [comment]
Although I hear you, I am reluctant of this. Here are my reasons:

1. It comes with a pretty good explaination of how to integrate this shortcode into the theme (although written for the predecessor - the Learn theme - it still applies to this theme, too). So if you want to use it, you are pretty well covered here.
2. Only few projects will benefit from this (mainly educational projects)
3. To make it integrate well into the theme there is still some work to do:
    1. put all files into the themes distribution as we don't allow external resources
    2. add on demand loading for the script files only if a quiz is referenced (like Mermaid or Swagger)
    3. integrate with the theme variants to allow styling based on the selected variant

Additionally, there are some things I dislike with the quizzes' implementation: 

1. It references to svelte CSS styles. I haven't disect the code but are not willing to introduce an optionated framework dependency. If svelte is not needed at all, references to it should be removed from quizzes' code to be sure it does not mess up if svelte was added by a user of the Relearn theme.
2. It bundles Font Awesome. This means, it will be loaded twice on a quiz page, onces by the theme and once by the quiz bundle. Because of Font Awesome's size, this is pretty much unacceptable for me.

**Comment by Prakash4844** [comment]
> It comes with a pretty good explaination of how to integrate this shortcode into the theme (although written for the predecessor - the Learn theme - it still applies to this theme, too). So if you want to use it, you are pretty well covered here.

You are certainly right about it. it was easy to get it working with Relearn Theme.

> It bundles Font Awesome. This means, it will be loaded twice on a quiz page, onces by the theme and once by the quiz bundle. Because of Font Awesome's size, this is pretty much unacceptable for me.

Didn't knew that, i guess my site is loading font awesome twice now. will have to see what can be done about it.
Thanks for pointing it out.

**Comment by cagix** [comment]
@McShelby Yeah, you're right. Using of the shortcode seems to be quite straightforward, yet at the same time you would be violating your coding rules by integrating it directly.

But I think that such a functionality out of the box would be quite nice. After all, your theme is called "Relearn theme" - to me it sounds like a theme for the educational environment ;-)
