### ISSUE TITLE
Upgrade Fontawesome ?

### ISSUE THREAD

**Issue by Xarkam** [McShelby/hugo-theme-relearn#525]
Hello, I am preparing a site with your theme and I have just noticed that it is impossible to have the social network icons in the version of fontawesome provided in the form of css.

I updated to version 6 and the icons are visible with this version.

Would it be possible to update the theme?

Thanks.

**Comment by McShelby** [comment]
Sorry, my previous comment went missing:

Because the theme still supports IE11, Font Awesome 6 is not an option as it is not compatible.

I already made an ill attempt in #151 and reverted it in #191.

If you want to use Font Awesome 6 you could try to download it on your own and place the various files in your own project's `static/css` and `static/webfonts` directory respectively.

**Comment by postb99** [comment]
I think it's totally a good idea to drop IE11 support, just bump major version of theme. Or someone else will do the cleanup a day.

**Comment by McShelby** [comment]
I will do the cleanup - once my company dropped IE11 support ;-)
