### ISSUE TITLE
Strange behavior when zooming Mermaid

### ISSUE THREAD

**Issue by hugograf** [McShelby/hugo-theme-relearn#628]
Since some versions of hugo-theme-relearn, zooming Mermaid does not work as expected.

See for example:
`https://grafioschtrader.github.io/gt-user-manual/de/admindata/taskdatachangemonitor/index.html`
or also
`https://grafioschtrader.github.io/gt-user-manual/de/watchlistinstrument/index.html`

The text/code can be found at [gt-user-manual](https://github.com/grafioschtrader/gt-user-manual)

**Comment by McShelby** [comment]
Hi, thanks for reporting.

> zooming Mermaid does not work as expected

What do you mean by that? Using Pointer events by using two fingers on a track pad of my Windows notebook works as expected with your example.

The last fix was in version 5.19.0 which is used in your examnple.

**Comment by hugograf** [comment]
You are right. It works flawlessly on almost all platforms. The problem relates to Google Chrome (not Firefox and Edge) in a Windows 11 environment.  Unfortunately, I don't have a second Windows 11 where I can verify this behavior. The scaling step is huge (for WheelEvent, the deltaY is: 2350) when using the mouse scroll wheel. When this is done, the chart gets lost and disappears completely. Surprisingly, zooming works in Chromium on Linux or Chrome on Windows 10. You are probably not responsible for this and can close this issue.

**Comment by McShelby** [comment]
I couldn't reproduce this even with a mouse (Logitech MX Master 3). I am also using Windows 11 and the latest Chrome - so the environment looks pretty much the same. Maybe you've reconfigured the step amount for the mouse wheel in your system settings?

Zooming is done by d3.js and I doubt that this is an issue on their side. Because of its wide popularity this should have been experienced by other users, too - which isn't as far as I know.

**Comment by McShelby** [comment]
@hugograf As I couldn't reproduce it in the way you described it, I saw a different issue with the Mermaid zoom and fixed it.

Maybe you want to give that fix a second try and report back?
