### ISSUE TITLE
topbar: make buttons configurable

### ISSUE THREAD

**Issue by ryanewtaylor** [McShelby/hugo-theme-relearn#639]
We have a use case where we would like readers that are uncomfortable directly editing our content to submit feedback using our Jira ticketing system. I am looking into creating a partial to add a feedback icon next to the edit button in the page header. Upon clicking it a new page would open to our designated URL to allow the user to submit a ticket for feedback.

If something like this would be useful for others could it be added to the core theme? The destination URL certainly would not need to be Jira but any URL useful for sending folks to a projects designated place for feedback.

**Comment by McShelby** [comment]
That was definetly a thing that was on my backlog. I've already seen a need for this in the [ksu-cs-textbooks/](https://github.com/ksu-cs-textbooks/hugo-theme-relearn) fork. But as no one was asking, I postponed it - until now.

First I thought I could use Hugos menu feature (as with the shortcut links), but because buttons may need to be shown in disabled state or omitted at all on certain conditions, I plan to do it differently.

![grafik](https://github.com/McShelby/hugo-theme-relearn/assets/11670870/4690de71-e20e-42e0-b981-96f6560164b2)

The right buttons of the header will be completly configurable by the user.
The defaults for the theme will not change compared to now. 
The primary area will always be displayed.
The secondary area will be displayed in desktop mode but will move to the tertiary area on mobile.
The tertiary button will only be visible if something needs to be displayed - either by explicitly putting something into it by the user or on mobile if secondary items are moved over.
The tertiary button **will not** be configurable.
Pressing the tertiary button will open an overlay similar to the toc showing items vertically..
If secondary and tertiary items are shown together in the overlay, they will be divided by a horizontal ruler.

To configure the areas, a new directory structure will be established. The following shows the proposed strucutre coming with the theme. As always, you can redefine those files in your own `layouts/partials/topbar` folder to your liking.

````
- layouts
  - partials
    - topbar
      - primary
        - 1.html
        - 2.html
      - secondary
        - 1.html
        - 2.html
      - tertiary
      - topbar-button.html
      - prev.html
      - next.html
      - print.html
      - edit.html
 ````

Each of `primary`, `secondary`, and `tertiary` can contain files numberd starting with `1` and will be displayed from right to left in the topbar or top down in the overlay. The numbers must be sequential, the built of the areas will stop when the sequence breaks.

`topbar-button.html` will be the default implementation for defining topbar buttons much similar to the current button shortcode.

For the themes default functionality, there will be predefined buttons in `prev`, `next`, `print` and `edit`.
In the themes default configuration
 - `primary/1` calls `next`
 - `primary/2` calls `prev`
 - `secondary/1` calls `print`
 - `secondary/2` calls `edit`

With this indirection you are free to easily use the default functionalities at different positions in the header without copying over the implementation.

Also you will be free to implement your sequential files as you like. If you decide not to display a button at all because of certain conditions, this will be pretty fine.

Does this sound reasonable?

**Comment by McShelby** [comment]
While the above was a nice outline, implementing this proved some design flaws. Thats the reason why it's now implemented a bit differently but not less versatile. See https://mcshelby.github.io/hugo-theme-relearn/basics/topbar/index.html
