### ISSUE TITLE
docs: add Poésieland to showcase

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#696]
@postb99 For you!

**Comment by postb99** [comment]
Hello @McShelby I just updated and fixed the chart, please can you take a new screenshot for your showcase, now there are three datasets because I wanted to go into details (this was I occupied myself today with, sometimes holidays are fun for just coding), and most importantly I fixed the legend above the chart, the meaning was inversed.

What an honor to figure into this showcase, because in fact it doesn't show a lot of sites. I really like the Linux distro site theme variant.

**Comment by McShelby** [comment]
>  I fixed the legend above the chart

The outcome looks really great.

>  I really like the Linux distro site theme variant.

Me too. They did override some of the theme's style in their custom CSS which looks really great. Although it may be a bit of work to upgrade to a newer version of the theme as the DOM can change even with minor version releases.
