### ISSUE TITLE
theme: reorganize repo to reduce size

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#718]
As mentioned in the [official forum](https://discourse.gohugo.io/t/build-fails-with-a-theme-but-not-with-another-one-how-to-troubleshoot/47051/7?u=mcshelby) as well as in disscussion #686 (now deleted by @calalloo), the theme repo is quite big on your disc due to the fact that it contains the history of all the docs screenshots.

Outsourcing the docs is only part of the solution as it will not cause the cloned repo to shrink. So further actions are required:

- rewrite the repos history. This may results in new hashes for existing changesets. Implications for the users are currently unclear. 
    https://stackoverflow.com/a/61544937
    https://stackoverflow.com/a/65543374
- replace the repos history. Pointed out by @cagix [below](https://github.com/McShelby/hugo-theme-relearn/issues/718#issuecomment-1807050520).
- archive this repo and restart with a fresh one. This will cause the loss of GitHub stars as well as issue notes, discussions and the old history only available thru the archived repo

I will investigate the options in the above order.

**Comment by cagix** [comment]
honestly, i'm not sure if it's worth your time. if the complete history is too large (300 mb currently?) one can always get a shallow clone. this should be documented, probably.

that said, you could split the theme folder and it's history to into a new repo using git filter-branch. however, it is quite convenient to have _one_ self contained repo instead of things sprawled over several repos imho (you'd need to keep all repos in sync then).

also, i've seen somewhere a technique where you continue your work in a fresh repo and the old repo being git linked somehow to the new one. but that wouldn't solve the underlying issue - your new repo _will_ grow, especially when you change screenshots and images a lot.

**Comment by McShelby** [comment]
Living in a 1st world country is a privilege but often we (I often do!) take it for granted. On a slow network this can quickly get annoying.

> one can always get a shallow clone (or just use the release artefacts). this should be documented, probably.

I am not sure if this will work if the theme is included as a go submodule.

I have a subtle hope, that the commit id's will be changed in a compatible way by [git-filter-repo](https://github.com/newren/git-filter-repo/). Having the old commit id's vanish is not acceptable. I then would probably go the second route.

The modified repo would still come with a very limited `exampleSite`. This also adds the opportunity to provide a `config.toml` that is configured to best practices / recommended settings while not changing default values in the them itself.

Syncing the docs repo with the theme repo should be manageable automatically by `repository_dispatch` events as lined out in the second stackoverflow link above.

The good(?) thing is: The repo is already big for quite some time. So there is no immediate need to do it right now as long as I keep updates to images resonable.

This task may be something for a cold winter holiday. Let's hope it will get cold this winter ;-)

**Comment by cagix** [comment]
> > one can always get a shallow clone (or just use the release artefacts). this should be documented, probably.
> 
> 
> 
> I am not sure if this will work if the theme is included as a go submodule.

good point, but i'm failing to imagine a use case which wouldn't allow me to change the method of inclusion... 


> 
> I have a subtle hope, that the commit id's will be changed in a compatible way by [git-filter-repo](https://github.com/newren/git-filter-repo/). Having the old commit id's vanish is not acceptable. I then would probably go the second route.

well, in my experience you get to keep the relevant history (commits, dates, ...), but (nearly?) all commit id's will be rewritten when using filter-branch. i don't think there is a way of splitting a repo and keeping the original commit id's.



> 
> The modified repo would still come with a very limited `exampleSite`. This also adds the opportunity to provide a `config.toml` that is configured to best practices / recommended settings while not changing default values in the theme itself.

but isn't the example site changing quite often (containing images)? and isn't the example site a kind of living documentation and should be in the "documentation" repo?

wouldn't it be better for users using go submodules to have just the theme as separate small repo?



> 
> Syncing the docs repo with the theme repo should be manageable automatically by `repository_dispatch` events as lined out in the second stackoverflow link above.

hmmm, that's just handling synchronised releases using github workflows?

including the theme repo via git submodule into the main repo would allow users to clone just one repo instead of several repos.

**Comment by cagix** [comment]
@McShelby they claim they in the readme of the git-filter-repo

> [Old commit references] Provide a way for users to use old commit IDs with the new repository (in particular via mapping from old to new hashes with refs/replace/ references).

if this really holds true, you could refactor the non-theme stuff away into a new repo and thus keeping your stars and the mapped commit id's in the smaller theme repo.

**Comment by McShelby** [comment]
> > The modified repo would still come with a very limited exampleSite. This also adds the opportunity to provide a config.toml that is configured to best practices / recommended settings while not changing default values in the theme itself.

> but isn't the example site changing quite often (containing images)? and isn't the example site a kind of living documentation and should be in the "documentation" repo?

This _new_ exampleSite would change quite infrequently as it would be more in the manner of `hugo new site`

> if this really holds true, you could refactor the non-theme stuff away into a new repo and thus keeping your stars and the mapped commit id's in the smaller theme repo.

That's my straw. Sounds almost to good to be true.

**Comment by cagix** [comment]
@McShelby you could also consider "git replace" (https://git-scm.com/book/en/v2/Git-Tools-Replace) and retire the old history to a new repo and continue work in this repo with the last (few) commit(s). in the example the last commit in the old repo and the first one in the new repo are linked, so developers can get the complete history if needed. and it comes without rewriting history and it keeps stuff in a single repo :)

**Comment by McShelby** [comment]
Thanks @cagix. It's always good to have alternatives here.

**Comment by McShelby** [comment]
I decided to leave it as is.

While it is correct, that the size of the repo is huge and will getting significantly bigger with the adding updated screenshots, it is only an issue in development. This is also the case with the case mentionend in the official forum. It could have been circumvented by adding `--depth 1` to `git clone`.

While the documented installation methods using a zip archive and hugo modules do not suffer from a big repo, `git submodules` does. This can be avoided by also adding `--depth 1`. I've updated the docs accordingly.
