### ISSUE TITLE
Support for Google Analytics

### ISSUE THREAD

**Issue by gmiejski** [McShelby/hugo-theme-relearn#731]
Hi, my use case is more general and I'd like to add Google Analytics to the page. 

I love your theme but I couldn't find neither the docs for this or plans in roadmap. 

Is it possible to apply GA easily to the theme? 

Thanks a lot for your answer!

**Comment by McShelby** [comment]
hugo comes with a default implemenation for GA https://gohugo.io/templates/internal/#configure-google-analytics

You can easily put it into your `custom-header.html` or `custom-footer.html`. See the docs here: https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html#partials

**Comment by dahlsailrunner** [comment]
Hi @gmiejski - I just came across this issue since I was trying to do the same thing and looking for an answer.  

The links @McShelby posted above are right on.  You need to do two things to make it work with this theme:

1. Add the configuration to `config.toml`:
```toml
[services]
  [services.googleAnalytics]
  ID = 'G-MEASUREMENT_ID'
```
2. Create (probably) a new file in `/layouts/partials` called `custom-header.html` (or `custom-footer.html`) and put the following into it:
```
{{ template "_internal/google_analytics.html" . }}
```

**Comment by gmiejski** [comment]
Thanks! 

Finally what I've done is I've added the google tag script as custom-header.html and it works like a charm. 
Thanks for help  and an awesome hugo theme 👍

**Comment by hvddrift** [comment]
I am trying to add a Umami script to the header as shown here:
![image](https://github.com/McShelby/hugo-theme-relearn/assets/972926/705d94f3-9301-40ff-866f-16d0fa8ae8c4)

It is not working correctly, just want to see if this is wrong.

![image](https://github.com/McShelby/hugo-theme-relearn/assets/972926/46575faf-6c74-4962-96ed-06a96f1bfb9f)

**Comment by McShelby** [comment]
Hi Hans. As mentioned in previous issues: Don't edit anything in your `themes` directory. This will make it nearly hard for you once you want to update the theme to a newer version.

You can copy the original `themes/hugo-theme-relearn/layouts/partials/custom-header.html` file over to `layouts/partials/custom-header.html` and make your changes there.

Hugo will "see" that you are providing your own `custom-header.html` and will use this instead of the one from the `themes` directory.

Besides of this, even your solution should work. 

> It is not working correctly

What specifically doesn't work?

**Comment by hvddrift** [comment]
Your right again :)

Placed the script in ```layouts/partials/custom-header.html``` and all works perfectly

Thank you.
