### ISSUE TITLE
link: fix links to pages containing dots in their name

### ISSUE THREAD

**Issue by andi-blafasl** [McShelby/hugo-theme-relearn#748]
I'm trying to find out how the new linking system is working but struggling with it.

In the past we where using "ref" shortcode to get the links working with and without uglyURLs enabled. It worked flawlessly, but made the MarkDown and the typing complicated.

You can checkout the behavior at our Repo https://github.com/BITS-Training/BITS-hugo/
The working version with Theme v5.3.x is in the [main](https://github.com/BITS-Training/BITS-hugo/blob/main/content/01%20lektion%20e-mails/11.Zusammenfassung.de.md?plain=1) Branch. The my first try with the new Theme v5.23.x is in the [develop](https://github.com/BITS-Training/BITS-hugo/blob/develop/content/01%20lektion%20e-mails/11.Zusammenfassung.de.md?plain=1) Branch

You can try both uglyURL settings with the two Environments "dev" (ugly disabled) and "html" (ugly enabled) both are using relativeURLs=true

In the content "/01-lektion-e-mails/11.zusammenfassung" there are two links. The first link is pointing to "/ansprechpersonen/", which is a folder with an _index file. The second link is pointing to "../10.netiquette" with is another file "10.Netiquette.de.md" withing the same directory.
I'm not sure if this is a different thing and I'm also not very firm with every thing like bundles, leafs and whatever there is in Hugo terms 😉 Maybe I also just don't know how to link in Hugo anyways 🤷 Any help very much appreciated 😊 

I observe the following behavior with the new Theme 
ugly false:
- first link links to "/ansprechpersonen/" 
  - working as expected
- second link links to "/01-lektion-e-mails/10.netiquette"
  - is working, but missing the trailing slash

ugly true:
- first link links to "/ansprechpersonen.html"
  - working as expected
- second link links to "/10.netiquette"
  - not working at all, not as expected.

I tried many different version of the Link like:
- `["Netiquette“](../10.netiquette)`
- `["Netiquette“](10.netiquette)`
- `["Netiquette“](./../10.netiquette)`
- `["Netiquette“](./10.netiquette/)`

none of this produced a working link with ugly true.

**Comment by McShelby** [comment]
First note: I will edit this answer for each new insight I gain.

This is for _ugly:true_ and second link to _/10.netiquette_

- the theme falsly recognises the `10.netiquette.de.md` link as "old style", where links could contain file extensions and leaves it unresolved. This is due to the dot in your file name.
- after fixing the above check in my debug version, Hugo stumbles across a similar error. See https://github.com/gohugoio/hugo/issues/10864
- after fixing the filename to `10_netiquette.de.md` Hugo behaves strangely but in a documented way https://gohugo.io/methods/page/getpage/ Nevertheless this strange behavior was the reason to initially introduce "portable Markdown links" with theme version 5.23. Seems it does not work out in all configurations.

Currently (without any theme fixes) you can not use relative links for all configuration permutations. You still need to change your links. In the above case to `["Netiquette“](10_netiquette)`

**Comment by andi-blafasl** [comment]
Thank you so much for the quick investigation and the suggestions on how to solve / work around the problem. I think we will go with filenames like `10-Netiquette.de.md` for now.

Found another thing that is not working. Linking to anchors:

- `[Passwörter](/03 lektion passwoerter/02-Gefahren#social-engineering)`

is ignored completely and just output as text.

**Comment by McShelby** [comment]
For your initial post I've now tested it with the current dev version of Hugo (0.123.0.dev) and the issue with dots in the name is resolved in Hugo. Nevertheless, this needs also a fix in the theme which is not applied, yet. And I'm a bit reluctant about it as it is quite delicate. Still thinking about it.

I've made some tests and these are the results (with Hugo 0.123.0.dev and a patched theme). Forms written in fat and an exclamation mark in front are not working with the specified configuration:

````
- Achten Sie auf die ["Netiquette“](./.././10.Netiquette/.). _default dev **!html**
- Achten Sie auf die ["Netiquette“](./.././10.Netiquette). _default dev **!html**
- Achten Sie auf die ["Netiquette“](.././10.Netiquette). _default dev **!html**
- Achten Sie auf die ["Netiquette“](../10.Netiquette). _default dev **!html**
- Achten Sie auf die ["Netiquette“](10.Netiquette). **!_default** **!dev** html
- Achten Sie auf die ["Lektion“](../). **!_default** **!_dev** **!html**
- Achten Sie auf die ["Lektion“](../.). _default dev **!html**
- Achten Sie auf die ["Lektion“](.). **!_default** **!dev** html
- Achten Sie auf die ["Zusammenfassung“](.). _default dev **!html**
- Achten Sie auf die ["Zusammenfassung“](). _default dev html
````

So sadly relative linking is still dependend on the `uglyURLs` setting, which is a pitty but it is at is for now. There is at least one form that currently works.

Your last post about the fragment identifier is a pure Hugo/Goldmark issue with spaces in file names. There is nothing I can do about it and I am not sure if this can/would ever be fixed in Hugo.

**Comment by McShelby** [comment]
I've made a push.

The implementation has the characteristics described in my previous post. This is in sync with the upcoming Hugo 0.123.0 behavior.

Sadly, this means, that currently there is still a difference how to link to other pages depending on your `uglyURLs`  setting.

@andi-blafasl  Are you running build for your project in both configurations or was this just for testing?
