### ISSUE TITLE
Hugo 0.124 and non basic alphanum in taxonomy terms, custom page directory name

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#815]
Just tried today's freshest version of theme (pulled the repo) with Hugo 0.124 instead of 0.123. Using Windows.

It works fine but I have issues again with taxonomy term custom page issue, and fixed it because it's just a matter of logic.

My custom term can be "eté" or "ombres et lumières" or "aimé (amant)". With accents or other symbols.

Now custom page should reside in a folder whose name contains this accent and symbols, unlike with Hugo 0.122 where the cleaned term worked.

So "eté", "ombres-et-lumières" and "aimé-(amant)". Not anymore "ete", "ombres-et-lumieres" and "aime-amant".

Not intuitive and not user-friendly. Maybe this change deserves a side note in theme's documentation ?

**Comment by McShelby** [comment]
Well, this is basically a Hugo issue and in flux since 0.123. They went thru different iterations related to accents and capitalization and I lost a bit track of the current state.

I guess the best for you is to stay with 0.122 for a while until the dust has settled. If you are interested you can take a look into Hugo's discussion forum or the repo issues and (maybe?) their relese notes.

**Comment by postb99** [comment]
Argh need to update theme again, layout is broken on mobile with menu left open or maybe the content custom width causes issue
