### ISSUE TITLE
search: improve generation of dedicated search page

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#888]
Currently the dedicated search page causes the code to be littered with special cases. While this in itself isn't an issue for the functionality, it is in regards to caching.

This is because, the home page needs to be patched for its title and URL in case we are in output format `searchpage` and therefore it is not cacheable and requires us to detect the output format during runtime in may occassions - which is a real hassle in itself.

To improve build time in #685 we need to get rid of this.

**Comment by postb99** [comment]
Hello, since you intend a rework, an additional thought :) Maybe this could better be seen as new issue/wishes?

After reading Lunr documentation I found out that you decided to keep multi-term search to be only "ORed" and this is not my cup of tea but is basically Lunr's one :D but your configuration prevents using it. I would prefer a search that check for presence of every entered term, by design (especially for my site, lol). I would love to have feedback from other users that use the theme.

Secondly, you also prevented wildcard search, but I would like to try it once.

However I'm fully ok with removing tilde (fuzzy search) or caret (negation) because in French caret can be used for linking two words (two search terms then) or building a compound word (that I think would better give several search terms too).

A typical example where I can't find what I look for on my site is "arc-en-ciel" that would be better break into 3 search terms and all of them required for match.

It seems that you removed Lunr stemmers but you see to keep shipping stemmer files. Another thing that would be explained. Did you notice issues when keeping stemmers and your custom boosts?

Theme search page code:

- https://github.com/McShelby/hugo-theme-relearn/blob/3a0ae52e610bbf99e6a4182a1d7889954e9b7d26/static/js/search.js#L137 this removes special chars
- https://github.com/McShelby/hugo-theme-relearn/blob/3a0ae52e610bbf99e6a4182a1d7889954e9b7d26/static/js/search.js#L33 this removes stemmers?
- https://github.com/McShelby/hugo-theme-relearn/blob/3a0ae52e610bbf99e6a4182a1d7889954e9b7d26/static/js/search.js#L144 I'm fine with this

Lunr documentation:
- https://lunrjs.com/guides/searching.html#term-presence "OR" search by default, altered with "+" and "-" characters, also fuzzy search with "~".
- https://lunrjs.com/guides/searching.html#wildcards

Cheers

**Comment by McShelby** [comment]
Hi Barbara, I moved your thoughts into #890.

This issue is only about structuring code in files and will result in identical functionality as before this change.

**Comment by McShelby** [comment]
Back to this ticket. Note for myself:

Take 1 failed. I tried to use `ExecuteAsTemplate` to create a dedicated search page. While it basically worked it has the negative side effect in completly ignoring the `relativeURLs` setting. This leads to invalid links on the search page. I am not sure if this is a bug of Hugo or a feature, as resources generated by `ExecuteAsTemplate` are not part of Hugo's known logical structure and theirfore may be ignored by intent for applying the `relativeURLs`  setting.

Back to the drawing board.
