### ISSUE TITLE
include: render shortcodes if `file` is a page

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#916]
Currently, the include shortcode can not render shortcodes if the file points to a page. This can be changed easily.

For resources or plain files, this isn't possible.

**Comment by McShelby** [comment]
Reverted the change back, as it is seen as a bad idea. Avoid the support hassle.

https://github.com/gohugoio/hugo/issues/12854

**Comment by postb99** [comment]
Well, after you did the change and before you reverted it, I just for fun included a "tag/XXX" autogenerated page in a regular page. Not very useful because there was only the taxonomy term page custom content displayed, not tag-related pages listing, but at least no compilation error when building site. Maybe I'm off topic with my test.
