### ISSUE TITLE
Does theme overrides tab width to 8 spaces instead of 4 by default?

### ISSUE THREAD

**Issue by sedyh** [McShelby/hugo-theme-relearn#928]
I'm not sure if this is connected to theme, but I found thats default tab size became 8 during rendering.

Default size:
![tabs-4-spaces](https://github.com/user-attachments/assets/79d3e187-1733-427f-bbe8-ecbc35aede7d)

Which renders like this:
![tabs-8-space](https://github.com/user-attachments/assets/fb199bb1-85d8-4b0d-8113-ebd60c00143c)

As far as I know hugo has 4 by default, is there a setting for this in the theme?
![image](https://github.com/user-attachments/assets/46feed8b-1104-486d-8420-1bb44411b2b1)

I guess it have something with the goldmark settings? But I don't set any special params for it. Setting it manualy doesn't work, does theme overrides it somewhere?
```
[markup.highlight]
    tabWidth = 4
```

**Comment by McShelby** [comment]
Nice find. I don't use tabs, so I never stumbled upon that.

The theme displays the unedited code output, generated by Hugo. As your quoted docs just say, the `tabWidth` is ignored in your case, because you also set `noClasses=false`

You can adjust the tab width manually, by overriding `layouts/partials/custom-header.html` with

````
<style>
  .highlight {
    tab-size: 4;
  }
</style>
````

**Comment by sedyh** [comment]
> Nice find. I don't use tabs, so I never stumbled upon that.
Me to, but gofmt forces to use them as far as I remember.
