### ISSUE TITLE
theme: page version selector

### ISSUE THREAD

**Issue by sedyh** [McShelby/hugo-theme-relearn#944]
Is it possible to add a little selector in the top bar section for page versions?
![image](https://github.com/user-attachments/assets/b80e8b5d-5d4f-44a8-9771-536a061d24af)
![image](https://github.com/user-attachments/assets/8ea52193-1b78-4a7f-b4cf-30c9bfbf9f0a)
It could be marked in the header section for each page:
```
+++
title = "Toggle"
weight = 1
version = 1.0.0
+++
```
And a little link shortcode that will switch the page version like:
> This property is deprecated, it was changed in [1.0.0]().

**Comment by McShelby** [comment]
Currently, the topbar only supports buttons or area buttons. [With the latter](https://mcshelby.github.io/hugo-theme-relearn/configuration/customization/topbar/index.html#area-button) you may could achieve something similar to a version selector but you have to build this yourself.

I know a few themes, that support such version selection (I guess Docsify at least). As far as I know, it is a bit of a hack because Hugo does not support arbitrary "axes" to manage this in a common way.

If Hugo implements arbitrary axes, versioning would be a feature I consider to include in the theme.
