### ISSUE TITLE
variant: fix importing base variants

### ISSUE THREAD

**Issue by bwbecker** [McShelby/hugo-theme-relearn#974]
Hi -- First, thanks for the incredible theme!  I have about half a dozen sites running with it.

In the documentation at https://mcshelby.github.io/hugo-theme-relearn/configuration/branding/colors/index.html#modifying-variants the code sample says:

```
@import "theme-relearn-light.css";

:root {
  --CODE-theme: neon; /* name of the chroma stylesheet file */
  --CODE-BLOCK-color: rgba( 226, 228, 229, 1 ); /* fallback color for code text */
  --CODE-BLOCK-BG-color: rgba( 40, 42, 54, 1 ); /* fallback color for code background */
}
```

This did not work for me until I changed `@import "theme-relearn-light.css";` to `@import "theme-relearn-light";`

**Comment by bwbecker** [comment]
OK, I'm confused...  It changed for me when I dropped the ".css" as described.  However, when I changed to a different color and reloaded (and stopped the hugo server and restarted), it didn't change to the new color.  Furthermore, I see in the MDN documentation that `import` does include the `.css`.

What I'm really trying to do is change the background behind the logo.  I think that should be `--MENU-HEADER-BG-color`.  Here's my `assets/css/theme-localpr.css` file:

```
@import url("theme-relearn-light.css");

:root {
    --MENU-SECTIONS-BG-color: blue;
    --MENU-SECTION-SEPARATOR-color: red;
    --MENU-HEADER-BG-color: red;
}
p {
    color: red;
} 
```
and I have this in my `hugo.toml` file:
```
[params]
  themeVariant = 'localpr'
```
The above DOES color my paragraphs red, so the file is being processed but I can't change the variables consistently.

Suggestions?

**Comment by McShelby** [comment]
Thanks for submitting.

You discovered a bunch of bugs, introduced lately. That said, the example _should_ work (but currently doen't).

First, the `@import` will be resolved during build and there is an error in the regex leading to invalid resulting CSS in your case.

Second, `@import url()` isn't supported (but will after the bug fix).

Third, you need to replace `:root {` in your example with `&:root {` (adding a leading ampersand).

While first and second are fixed in the latest push, I am working on a solution for the third. In the worst case I'll have to adjust the example in the docs but this would introduce a breaking change.

**Comment by bwbecker** [comment]
Thanks for the quick reply!  Much appreciated.

**Comment by McShelby** [comment]
I also pushed a fix for the third issue. Now it should behave as documented, but also your example from the second post should work.
